export const WHATSAPP = '51935211605';

export const CULTIVOS = [
  {
    id: 'papa',
    nombre: 'Papa',
    emoji: '🥔',
    categoria: 'basico',
    variedades: ['Yungay', 'Perricholi', 'Única', 'Canchán', 'Huayro', 'Peruanita'],
    ciclo: [
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 15,
        acciones: ['Preparar suelo con yunta o arado', 'Cortar semilla en trozos de 40-60g con 2-3 brotes', 'Plantar a 20cm de distancia y 15cm de profundidad', 'Aplicar fertilizante base (100-200 kg/ha de fosfato)'],
        alertas: ['No sembrar si hay heladas pronosticadas', 'Verificar que la semilla no esté afectada por tizón tardío'] },
      { id: 'germinacion',     nombre: 'Germinación',            emoji: '🌿', diasInicio: 15,  diasFin: 30,
        acciones: ['Controlar humedad del suelo (60-70%)', 'Aplicar fertilizante nitrogenado (urea)', 'Eliminar malezas emergentes', 'Vigilar brotes de color púrpura (virus)'],
        alertas: ['Humedad excesiva causa pudrición de tubérculo semilla', 'Falta de nitrógeno retrasa crecimiento'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 30,  diasFin: 60,
        acciones: ['Aplicar segunda dosis de nitrógeno', 'Realizar aporque (cubrir tallos con tierra)', 'Controlar plagas: polilla guatemalteca, gusano blanco', 'Fumigar contra tizón temprano si hay humedad alta'],
        alertas: ['Pluviometría alta favorece tizón tardío', 'Polilla guatemalteca ataca tallos'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 60,  diasFin: 75,
        acciones: ['Aplicar fungicida preventivo (copper o mancozeb)', 'No exceder nitrógeno (retrasa tuberización)', 'Monitorear flores para detectar anomalias', 'Mantener riego constante'],
        alertas: ['Exceso de nitrógeno produce tallo largo sin tubérculos', 'Floración irregular indica estrés hídrico'] },
      { id: 'tuberizacion',    nombre: 'Tuberización',           emoji: '🥔', diasInicio: 75,  diasFin: 120,
        acciones: ['Reducir riego gradualmente (2-3 semanas antes de cosecha)', 'Aplicar fungicida contra tizón tardío', 'No caminar entre surcos (compacta suelo)', 'Monitorear tamaño de tubérculos'],
        alertas: ['Riego excesivo causa tubérculos agrietados', 'Tizón tardío destruye cosecha en 2-3 días'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '⛏️', diasInicio: 120, diasFin: 150,
        acciones: ['Secar tallos 2 semanas antes (cortar o doblar)', 'Cosechar cuando piel no se raspe fácil', 'No exponer tubérculos al sol directo', 'Almacenar en lugar fresco y oscuro (10-15°C)'],
        alertas: ['Cosechar antes de heladas', 'Tubérculos verdes son tóxicos (no comer)'] },
    ],
  },
  {
    id: 'maiz',
    nombre: 'Maíz',
    emoji: '🌽',
    categoria: 'basico',
    variedades: ['Amarillo duro', 'Blanco gigante', 'Choclo', 'Morado'],
    ciclo: [
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 10,
        acciones: ['Germinar semilla previamente (remojo 12-24h)', 'Sembrar a 80cm entre surcos y 20cm entre plantas', 'Profundidad de 3-5cm', 'Aplicar abono de base (gallinaza o estiércol)'],
        alertas: ['Temperatura del suelo debe ser >12°C para germinar', 'No sembrar en suelo encharcado'] },
      { id: 'germinacion',     nombre: 'Germinación',            emoji: '🌿', diasInicio: 10,  diasFin: 20,
        acciones: ['Resiembra de plantas faltantes', 'Controlar primeras malezas', 'Mantener humedad uniforme'],
        alertas: ['Gusano cogollero puede atacar brotes jóvenes', 'Heladas tardías matan plántulas'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 20,  diasFin: 50,
        acciones: ['Primera escarda (desmalezar)', 'Aplicar nitrógeno (urea o sulfato de amonio)', 'Segunda escarda a los 35 días', 'Aplicar herbicida pre-emergente si es necesario'],
        alertas: ['Planta dominada por malezas pierde 50% rendimiento', 'Falta de nitrógeno = hojas amarillas'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 50,  diasFin: 65,
        acciones: ['Aplicar fertilizante de cobre y zinc', 'No fumigar cerca de abejas', 'Verificar polinización (choclo)', 'Mantener riego'],
        alertas: ['Estrés hídrico en floración = mazorcas vacías', 'Polilla del maíz ataca mazorcas jóvenes'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🌽', diasInicio: 65,  diasFin: 90,
        acciones: ['Monitorear humedad del grano (aplastar grano)', 'Controlar gusano del choclo', 'Raleo de mazorcas si plantó doble', 'Aplicar insecticida biológico (Bt) si hay plagas'],
        alertas: ['Gusano del maíz destruye mazorca completa', 'Exceso de humedad = hongos en grano'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🌽', diasInicio: 90,  diasFin: 120,
        acciones: ['Cosechar cuando grano está duro y cáscara seca', 'Cortar mazorcas y secar al sol 3-5 días', 'Almacenar en lugar seco y ventilado', 'Producción esperada: 3-6 ton/ha'],
        alertas: ['No cosechar con humedad >15% (se pudre)', 'Gusano del maíz puede infestar en almacenamiento'] },
    ],
  },
  {
    id: 'palta',
    nombre: 'Palta',
    emoji: '🥑',
    categoria: 'frutal',
    variedades: ['Hass', 'Fuerte', 'Criolla', 'Ettinger'],
    ciclo: [
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 21,
        acciones: ['Germinar semilla en bolsa (sin pelar, mitad arriba del agua)', 'Trasplantar cuando tallo tenga 20-30cm', 'Plantar a 8-10m de distancia entre árboles', 'Proteger del sol directo los primeros meses'],
        alertas: ['La palta de hueso tarda 5-7 años en producir', 'Variedades injertadas producen a los 3-4 años'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 21,  diasFin: 180,
        acciones: ['Fertilizar cada 3 meses con NPK 15-15-15', 'Mantener riego constante (2-3 veces/semana)', 'Controlar gusano del brote (poda de ramas dañadas)', 'Mulching con paja o plástico negro'],
        alertas: ['Gusano del brote perfora tallos nuevos', 'Falta de agua = caída de hojas'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 180, diasFin: 210,
        acciones: ['No aplicar insecticidas (mata polinizadores)', 'Atraer abejas con flores companion', 'Reducir nitrógeno, aumentar fósforo', 'Mantener humedad estable'],
        alertas: ['Floración masiva no garantiza fruta (necesita polinización cruzada)', 'Hass requiere polinizador compatible (Fuerte, Ettinger)'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🥑', diasInicio: 210, diasFin: 300,
        acciones: ['Raleo de frutos pequeños (dejar 1 por cada 20cm)', 'Aplicar calcio para evitar pudrición apical', 'Monitorear tamaño del fruto', 'Cubrir frutos con redes si hay pájaros'],
        alertas: ['Pudrición apical = falta de calcio', 'Pájaros picotean frutos maduros'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🥑', diasInicio: 300, diasFin: 365,
        acciones: ['Cosechar cuando fruto alcance tamaño comercial', 'No esperar a que se ablande en el árbol', 'Cosechar con cuidado (lastimaduras reducen vida)', 'Madurar fuera del árbol a 15-20°C'],
        alertas: ['Fruto maduro en árbol se cae y se daña', 'No refrigerar bajo 5°C (daño por frío)'] },
    ],
  },
  {
    id: 'arandano',
    nombre: 'Arándano',
    emoji: '🫐',
    categoria: 'frutal',
    variedades: ['Biloxi', 'Emerald', 'Jewel', 'O\'Neal'],
    ciclo: [
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 30,
        acciones: ['Preparar suelo ácido (pH 4.5-5.5)', 'Plantar a 1.5m entre plantas y 3m entre surcos', 'Agregar turba o aserrín al suelo', 'Mulching con paja de arroz 10cm'],
        alertas: ['Suelo con pH >6.0 mata la planta', 'Raíces superficiales necesitan riego por goteo'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 30,  diasFin: 120,
        acciones: ['Riego por goteo diario (1-2L/planta/día)', 'Fertilizar con sulfato de amonio cada 15 días', 'Poda de ramas viejas en invierno', 'Controlar pájaros con malla azul'],
        alertas: ['Clorosis en hojas = pH alto o hierro insuficiente', 'Pájaros pueden destruir 80% de la cosecha'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 120, diasFin: 150,
        acciones: ['No aplicar productos químicos', 'Atraer abejas melíferas', 'Cubrir con malla anti-granizo si es necesario', 'Mantener riego constante'],
        alertas: ['Heladas tardías destruyen flores', 'Polinización insuficiente = frutos pequeños'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🫐', diasInicio: 150, diasFin: 200,
        acciones: ['Cubrir con malla anti-pájaros', 'Riego aumentar a 3L/planta/día', 'Monitorear color de fruto (verde→rojo→azul)', 'No fumigar 14 días antes de cosecha'],
        alertas: ['Fruto rojo atrae pájaros inmediatamente', 'Exceso de riego = frutos agrietados'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🫐', diasInicio: 200, diasFin: 240,
        acciones: ['Cosechar solo frutos azules completos', 'Cosechar cada 3-7 días según maduración', 'Refrigerar inmediatamente a 0-2°C', 'Producción: 4-8 kg/planta/año'],
        alertas: ['Fruto blanco no madura fuera del árbol', 'Manejar con cuidado (se aplasta fácilmente)'] },
    ],
  },
  {
    id: 'cana',
    nombre: 'Caña de azúcar',
    emoji: '🎋',
    categoria: 'industrial',
    variedades: ['NA56', 'CC01-941', 'SP71-6949', 'CP52-43', 'H59-3774'],
    ciclo: [
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 20,
        acciones: ['Cortar caña en semilla de 3-4 yemas', 'Plantar a 1.5m entre surcos y 1m entre tallos', 'Cubrir con 5-8cm de tierra', 'Aplicar abono de base (gallinaza 10 ton/ha)'],
        alertas: ['Semilla vieja (>30 días) germina mal', 'Suelo seco requiere riego inmediato'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 20,  diasFin: 150,
        acciones: ['Primera escarda a los 30 días', 'Segunda escarda + aporque a los 60 días', 'Fertilizar con urea a los 45 y 90 días', 'Riego por surco cada 7-10 días'],
        alertas: ['Gusano taladrador de la caña perfora tallos', 'Roya de la caña en clima húmedo'] },
      { id: 'maduracion',      nombre: 'Maduración',             emoji: '🎋', diasInicio: 150, diasFin: 300,
        acciones: ['Reducir riego 2 meses antes de cosecha', 'No aplicar nitrógeno (reduce azúcar)', 'Aplicar regulador de crecimiento si necesario', 'Monitorear porcentaje de sacarosa'],
        alertas: ['Riego excesivo diluye azúcar', 'Quemar caña antes de cosecha (elimina plagas)'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '⛏️', diasInicio: 300, diasFin: 365,
        acciones: ['Cosechar cuando madurez alcanza 12-18 meses', 'Cortar a nivel del suelo (sin raíz)', 'Transportar al trapiche en <24 horas', 'Producción: 80-150 ton/ha/año'],
        alertas: ['Caña quemada pierde 20% de peso', 'No cosechar con escarcha (congela savia)'] },
    ],
  },
  {
    id: 'platano',
    nombre: 'Plátano',
    emoji: '🍌',
    categoria: 'frutal',
    variedades: ['Sedita', 'Bellaco', 'Isla', 'Palillo', 'Guineo'],
    ciclo: [
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 30,
        acciones: ['Usar cormo de planta madre como semilla', 'Plantar a 2.5m x 2.5m', 'Cavar hoyo de 40x40x40cm', 'Aplicar abono de base y humus de lombriz'],
        alertas: ['Cormos con nematodos propagan enfermedad', 'No plantar donde hubo plátano antes de 2 años'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 30,  diasFin: 270,
        acciones: ['Deschupar (eliminar hijuelos) cada 2 meses', 'Dejar solo el tallo principal + 1 reserva', 'Fertilizar NPK cada 3 meses', 'Controlar sigatoka con fungicida preventivo'],
        alertas: ['Sigatoka negra destruye hojas = menos foto-síntesis', 'Tallos débiles se quiebran con viento'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 270, diasFin: 300,
        acciones: ['Cortar la flor macho (macho seco)', 'Proteger racimo del sol (cubrir con hojas)', 'Acomodar tallo con estaca si está inclinado', 'No fumigar cerca de la flor'],
        alertas: ['Flor macho no cortada = frutos pequeños', 'Gusano del racimo perfora frutos'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🍌', diasInicio: 300, diasFin: 330,
        acciones: ['Cubrir racimo con bolsa plástica perforada', 'Eliminar hojas secas (mejorar ventilación)', 'Monitorear tamaño de frutos', 'Mantener riego constante'],
        alertas: ['Pájaros y murciélagos picotean frutos', 'Exceso de viento rompe racimos'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🍌', diasInicio: 330, diasFin: 365,
        acciones: ['Cosechar cuando frutos estén llenos pero verdes', 'Cortar tallo principal (dejar hijuelo)', 'Madurar en sombra a 14-18°C', 'Producción: 15-30 kg/planta/ciclo'],
        alertas: ['Fruto amarillo en árbol = demasiado maduro', 'No refrigerar bajo 13°C (daño por frío)'] },
    ],
  },
  {
    id: 'papaya',
    nombre: 'Papaya',
    emoji: '🍈',
    categoria: 'frutal',
    variedades: ['Hawaiana', 'Solo Sunrise', 'Tainung', 'Maradol', 'Venezolana'],
    ciclo: [
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 21,
        acciones: ['Germinar en bandejas con sustrato', 'Semilla remojada 48h previamente', 'Trasplantar cuando planta tenga 15-20cm', 'Plantar a 2m entre plantas'],
        alertas: ['Germinación lenta si temperatura <20°C', 'Plántulas extremadamente sensibles a exceso de agua'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 21,  diasFin: 120,
        acciones: ['Riego diario por goteo (2-3L/planta/día)', 'Fertilizar con NPK cada 15 días', 'Controlar chancro bacterial con cobre', 'Mulching para conservar humedad'],
        alertas: ['Chancro bacterial mata plantas jóvenes', 'Exceso de nitrógeno = tallo suave'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 120, diasFin: 150,
        acciones: ['No aplicar insecticidas (mata abejas)', 'Atraer polinizadores con flores companion', 'Mantener humedad constante', 'Aplicar calcio para prevenir pudrición'],
        alertas: ['Floración abundante no garantiza fruta', 'Virus de la papaya destruye plantaciones'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🍈', diasInicio: 150, diasFin: 180,
        acciones: ['Raleo de frutos (dejar 15-20 por planta)', 'Cubrir frutos con papel o bolsa', 'Aplicar fungicida contra antracnosis', 'Aumentar riego a 4L/planta/día'],
        alertas: ['Antracnosis mancha frutos (no son comerciales)', 'Mosca de la fruta pica frutos maduros'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🍈', diasInicio: 180, diasFin: 210,
        acciones: ['Cosechar cuando empiece a amarillar', 'No esperar a que esté totalmente madura', 'Manejar con cuidado (se daña fácil)', 'Producción: 30-60 frutos/planta/año'],
        alertas: ['Fruto maduro se pudre en 2-3 días', 'Cortar tallo base para obtener nueva plantación'] },
    ],
  },
];

