export const WHATSAPP = '51935211605';

export const CULTIVOS = [
  {
    id: 'papa',
    nombre: 'Papa',
    emoji: '🥔',
    categoria: 'basico',
    variedades: ['Yungay', 'Perricholi', 'Única', 'Canchán', 'Huayro', 'Peruanita'],
    ciclo: [
      { id: 'preparacion',     nombre: 'Preparación del terreno', emoji: '🚜', diasInicio: -30, diasFin: 0,
        acciones: ['Arar o jinear el terreno a 20-25cm de profundidad', 'Aplicar abono orgánico (estiércol o compost)', 'Nivelar el terreno para evitar encharcamientos', 'Analizar suelo y corregir pH si es necesario'],
        alertas: ['No preparar suelo muy húmedo (se forman terrones)', 'Aplicar cal si pH < 5.0'] },
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 15,
        acciones: ['Preparar suelo con yunta o arado', 'Cortar semilla en trozos de 40-60g con 2-3 brotes', 'Plantar a 20cm de distancia y 15cm de profundidad', 'Aplicar fertilizante base (100-200 kg/ha de fosfato)'],
        alertas: ['No sembrar si hay heladas pronosticadas', 'Verificar que la semilla no esté afectada por tizón tardío'] },
      { id: 'germinacion',     nombre: 'Germinación',            emoji: '🌿', diasInicio: 15,  diasFin: 30,
        acciones: ['Controlar humedad del suelo (60-70%)', 'Aplicar fertilizante nitrogenado (urea)', 'Eliminar malezas emergentes', 'Vigilar brotes de color púrpura (virus)'],
        alertas: ['Humedad excesiva causa pudrición de tubérculo semilla', 'Falta de nitrógeno retrasa crecimiento'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 30,  diasFin: 60,
        acciones: ['Aplicar segunda dosis de nitrógeno', 'Realizar aporque (cubrir tallos con tierra)', 'Controlar plagas: polilla guatemalteca, gusano blanco', 'Fumigar contra tizón temprano si hay humedad alta'],
        alertas: ['Pluviometría alta favorece tizón tardío', 'Polilla guatemalteca ataca tallos'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 60,  diasFin: 75,
        acciones: ['Aplicar fungicida preventivo (copper o mancozeb)', 'No exceder nitrógeno (retrasa tuberización)', 'Monitorear flores para detectar anomalias', 'Mantener riego constante'],
        alertas: ['Exceso de nitrógeno produce tallo largo sin tubérculos', 'Floración irregular indica estrés hídrico'] },
      { id: 'tuberizacion',    nombre: 'Tuberización',           emoji: '🥔', diasInicio: 75,  diasFin: 120,
        acciones: ['Reducir riego gradualmente (2-3 semanas antes de cosecha)', 'Aplicar fungicida contra tizón tardío', 'No caminar entre surcos (compacta suelo)', 'Monitorear tamaño de tubérculos'],
        alertas: ['Riego excesivo causa tubérculos agrietados', 'Tizón tardío destruye cosecha en 2-3 días'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '⛏️', diasInicio: 120, diasFin: 150,
        acciones: ['Secar tallos 2 semanas antes (cortar o doblar)', 'Cosechar cuando piel no se raspe fácil', 'No exponer tubérculos al sol directo', 'Almacenar en lugar fresco y oscuro (10-15°C)'],
        alertas: ['Cosechar antes de heladas', 'Tubérculos verdes son tóxicos (no comer)'] },
    ],
  },
  {
    id: 'maiz',
    nombre: 'Maíz',
    emoji: '🌽',
    categoria: 'basico',
    variedades: ['Amarillo duro', 'Blanco gigante', 'Choclo', 'Morado'],
    ciclo: [
      { id: 'preparacion',     nombre: 'Preparación del terreno', emoji: '🚜', diasInicio: -20, diasFin: 0,
        acciones: ['Arar el terreno a 20cm de profundidad', 'Aplicar estiércol o gallinaza (2-3 ton/ha)', 'Nivelar y marcar surcos a 80cm', 'Verificar pH del suelo (5.5-7.0 ideal)'],
        alertas: ['Suelo muy seco dificulta germinación', 'pH bajo reduce rendimiento'] },
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 10,
        acciones: ['Germinar semilla previamente (remojo 12-24h)', 'Sembrar a 80cm entre surcos y 20cm entre plantas', 'Profundidad de 3-5cm', 'Aplicar abono de base (gallinaza o estiércol)'],
        alertas: ['Temperatura del suelo debe ser >12°C para germinar', 'No sembrar en suelo encharcado'] },
      { id: 'germinacion',     nombre: 'Germinación',            emoji: '🌿', diasInicio: 10,  diasFin: 20,
        acciones: ['Resiembra de plantas faltantes', 'Controlar primeras malezas', 'Mantener humedad uniforme'],
        alertas: ['Gusano cogollero puede atacar brotes jóvenes', 'Heladas tardías matan plántulas'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 20,  diasFin: 50,
        acciones: ['Primera escarda (desmalezar)', 'Aplicar nitrógeno (urea o sulfato de amonio)', 'Segunda escarda a los 35 días', 'Aplicar herbicida pre-emergente si es necesario'],
        alertas: ['Planta dominada por malezas pierde 50% rendimiento', 'Falta de nitrógeno = hojas amarillas'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 50,  diasFin: 65,
        acciones: ['Aplicar fertilizante de cobre y zinc', 'No fumigar cerca de abejas', 'Verificar polinización (choclo)', 'Mantener riego'],
        alertas: ['Estrés hídrico en floración = mazorcas vacías', 'Polilla del maíz ataca mazorcas jóvenes'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🌽', diasInicio: 65,  diasFin: 90,
        acciones: ['Monitorear humedad del grano (aplastar grano)', 'Controlar gusano del choclo', 'Raleo de mazorcas si plantó doble', 'Aplicar insecticida biológico (Bt) si hay plagas'],
        alertas: ['Gusano del maíz destruye mazorca completa', 'Exceso de humedad = hongos en grano'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🌽', diasInicio: 90,  diasFin: 120,
        acciones: ['Cosechar cuando grano está duro y cáscara seca', 'Cortar mazorcas y secar al sol 3-5 días', 'Almacenar en lugar seco y ventilado', 'Producción esperada: 3-6 ton/ha'],
        alertas: ['No cosechar con humedad >15% (se pudre)', 'Gusano del maíz puede infestar en almacenamiento'] },
    ],
  },
  {
    id: 'palta',
    nombre: 'Palta',
    emoji: '🥑',
    categoria: 'frutal',
    variedades: ['Hass', 'Fuerte', 'Criolla', 'Ettinger'],
    ciclo: [
      { id: 'preparacion',     nombre: 'Preparación del terreno', emoji: '🚜', diasInicio: -60, diasFin: 0,
        acciones: ['Estacar puntos a 8-10m de distancia', 'Cavar hoyos de 60x60x60cm', 'Mezclar tierra con compost (50/50)', 'Instalar sistema de riego por goteo'],
        alertas: ['Raíces superficiales necesitan riego constante', 'No plantar en suelo compactado'] },
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 21,
        acciones: ['Germinar semilla en bolsa (sin pelar, mitad arriba del agua)', 'Trasplantar cuando tallo tenga 20-30cm', 'Plantar a 8-10m de distancia entre árboles', 'Proteger del sol directo los primeros meses'],
        alertas: ['La palta de hueso tarda 5-7 años en producir', 'Variedades injertadas producen a los 3-4 años'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 21,  diasFin: 180,
        acciones: ['Fertilizar cada 3 meses con NPK 15-15-15', 'Mantener riego constante (2-3 veces/semana)', 'Controlar gusano del brote (poda de ramas dañadas)', 'Mulching con paja o plástico negro'],
        alertas: ['Gusano del brote perfora tallos nuevos', 'Falta de agua = caída de hojas'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 180, diasFin: 210,
        acciones: ['No aplicar insecticidas (mata polinizadores)', 'Atraer abejas con flores companion', 'Reducir nitrógeno, aumentar fósforo', 'Mantener humedad estable'],
        alertas: ['Floración masiva no garantiza fruta (necesita polinización cruzada)', 'Hass requiere polinizador compatible (Fuerte, Ettinger)'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🥑', diasInicio: 210, diasFin: 300,
        acciones: ['Raleo de frutos pequeños (dejar 1 por cada 20cm)', 'Aplicar calcio para evitar pudrición apical', 'Monitorear tamaño del fruto', 'Cubrir frutos con redes si hay pájaros'],
        alertas: ['Pudrición apical = falta de calcio', 'Pájaros picotean frutos maduros'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🥑', diasInicio: 300, diasFin: 365,
        acciones: ['Cosechar cuando fruto alcance tamaño comercial', 'No esperar a que se ablande en el árbol', 'Cosechar con cuidado (lastimaduras reducen vida)', 'Madurar fuera del árbol a 15-20°C'],
        alertas: ['Fruto maduro en árbol se cae y se daña', 'No refrigerar bajo 5°C (daño por frío)'] },
    ],
  },
  {
    id: 'arandano',
    nombre: 'Arándano',
    emoji: '🫐',
    categoria: 'frutal',
    variedades: ['Biloxi', 'Emerald', 'Jewel', 'O\'Neal'],
    ciclo: [
      { id: 'preparacion',     nombre: 'Preparación del terreno', emoji: '🚜', diasInicio: -45, diasFin: 0,
        acciones: ['Corregir pH a 4.5-5.5 con azufre o turba', 'Cavar surcos de 30cm de profundidad', 'Instalar sistema de riego por goteo', 'Agregar material orgánico al suelo'],
        alertas: ['pH >6.0 mata las plantas', 'Suelo calcáreo es incompatible'] },
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 30,
        acciones: ['Preparar suelo ácido (pH 4.5-5.5)', 'Plantar a 1.5m entre plantas y 3m entre surcos', 'Agregar turba o aserrín al suelo', 'Mulching con paja de arroz 10cm'],
        alertas: ['Suelo con pH >6.0 mata la planta', 'Raíces superficiales necesitan riego por goteo'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 30,  diasFin: 120,
        acciones: ['Riego por goteo diario (1-2L/planta/día)', 'Fertilizar con sulfato de amonio cada 15 días', 'Poda de ramas viejas en invierno', 'Controlar pájaros con malla azul'],
        alertas: ['Clorosis en hojas = pH alto o hierro insuficiente', 'Pájaros pueden destruir 80% de la cosecha'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 120, diasFin: 150,
        acciones: ['No aplicar productos químicos', 'Atraer abejas melíferas', 'Cubrir con malla anti-granizo si es necesario', 'Mantener riego constante'],
        alertas: ['Heladas tardías destruyen flores', 'Polinización insuficiente = frutos pequeños'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🫐', diasInicio: 150, diasFin: 200,
        acciones: ['Cubrir con malla anti-pájaros', 'Riego aumentar a 3L/planta/día', 'Monitorear color de fruto (verde→rojo→azul)', 'No fumigar 14 días antes de cosecha'],
        alertas: ['Fruto rojo atrae pájaros inmediatamente', 'Exceso de riego = frutos agrietados'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🫐', diasInicio: 200, diasFin: 240,
        acciones: ['Cosechar solo frutos azules completos', 'Cosechar cada 3-7 días según maduración', 'Refrigerar inmediatamente a 0-2°C', 'Producción: 4-8 kg/planta/año'],
        alertas: ['Fruto blanco no madura fuera del árbol', 'Manejar con cuidado (se aplasta fácilmente)'] },
    ],
  },
  {
    id: 'cana',
    nombre: 'Caña de azúcar',
    emoji: '🎋',
    categoria: 'industrial',
    variedades: ['H32-8560', 'RB72-454', 'H57-5174', 'NA56', 'CC01-941', 'SP71-6949', 'CP52-43', 'H59-3774'],
    infoVariedades: [
      { nombre: 'H32-8560', descripcion: 'Variedad dominante en Costa Norte. Alta sacarosa, tolera salinidad moderada. Ciclo 12-16 meses.', rendimiento: '120-180 ton/ha', sacarosa: '14-16%' },
      { nombre: 'RB72-454', descripcion: 'Alta productividad, resistente a plagas comunes. Ideal para zonas de riego intensivo.', rendimiento: '130-200 ton/ha', sacarosa: '13-15%' },
      { nombre: 'H57-5174', descripcion: 'Tolerante a alta salinidad. Usada en campos con problemas de salitre. Demostrada resistencia.', rendimiento: '100-160 ton/ha', sacarosa: '13-14%' },
      { nombre: 'NA56', descripcion: 'Tolerante a sequía. Adaptada a zonas marginales.', rendimiento: '80-120 ton/ha', sacarosa: '12-14%' },
      { nombre: 'CC01-941', descripcion: 'Alta germinación, crecimiento rápido.', rendimiento: '100-150 ton/ha', sacarosa: '13-15%' },
      { nombre: 'SP71-6949', descripcion: 'Buena adaptación a suelos fríos de sierra.', rendimiento: '90-130 ton/ha', sacarosa: '12-13%' },
      { nombre: 'CP52-43', descripcion: 'Clásica variedad peruana, resistente a roya.', rendimiento: '80-120 ton/ha', sacarosa: '13-14%' },
      { nombre: 'H59-3774', descripcion: 'Buena calidad de jugo, tolerante a heladas leves.', rendimiento: '90-140 ton/ha', sacarosa: '13-15%' },
    ],
    ciclo: [
      { id: 'preparacion',       nombre: 'Preparación del terreno', emoji: '🚜', diasInicio: 0,   diasFin: 15,
        acciones: ['Arar y rastrillar a 30cm de profundidad', 'Nivelar el terreno para riego por gravedad', 'Aplicar abono de base: gallinaza 10-15 ton/ha + fosfato', 'Formar surcos a 1.5m de distancia'],
        alertas: ['Suelo compactado reduce rendimiento 30%', 'Análisis de suelo previo para detectar salinidad (CEe)'] },
      { id: 'siembra',           nombre: 'Siembra',                emoji: '🌱', diasInicio: 15,  diasFin: 30,
        acciones: ['Cortar caña sana en semilla de 3-4 yemas (25-30cm)', 'Plantar inclinada en surco, cubrir 5-8cm de tierra', 'Densidad: 100,000-120,000 plantas/ha', 'Aplicar insecticida contra broca de la caña'],
        alertas: ['Semilla vieja (>7 días desde corte) pierde viabilidad', 'No usar semilla de campos con mosaico (enfermedad viral)'] },
      { id: 'germinacion',       nombre: 'Germinación y macollaje', emoji: '🌿', diasInicio: 30,  diasFin: 60,
        acciones: ['Mantener humedad del suelo al 60-70%', 'Primera escarda mecánica a los 30 días', 'Controlar malezas con glifosato entre surcos', 'Evaluar porcentaje de germinación (>70% es aceptable)'],
        alertas: ['Sequía en germinación = pérdida de 40% de plantas', 'Exceso de humedad causa pudrición de yemas'] },
      { id: 'crecimiento',       nombre: 'Crecimiento vegetativo', emoji: '📏', diasInicio: 60,  diasFin: 180,
        acciones: ['Segunda escarda + aporque a los 60 días', 'Fertilizar con urea: 200 kg/ha a los 45 y 90 días', 'Riego por surco cada 7-10 días (30-40mm/semana)', 'Aplicar regulador de crecimiento si tallo es muy largo'],
        alertas: ['Gusano taladrador (Diatraea) perfora tallos', 'Roya de la caña (Puccinia) en clima húmedo', 'Mosca blanca transmite virus del mosaico'] },
      { id: 'maduracion',        nombre: 'Maduración',             emoji: '🍬', diasInicio: 180, diasFin: 300,
        acciones: ['Reducir riego 2-3 meses antes de cosecha (estrés hídrico)', 'NO aplicar nitrógeno (reduce contenido de azúcar)', 'Aplicar ethefon para maduración acelerada si necesario', 'Monitorear brix y sacarosa cada 15 días'],
        alertas: ['Riego excesivo diluye azúcar', 'Aplicar quemada controlada si hay plagas (solo donde sea legal)'] },
      { id: 'cosecha',           nombre: 'Cosecha y zafra',        emoji: '⛏️', diasInicio: 300, diasFin: 365,
        acciones: ['Cosechar a los 12-18 meses según variedad', 'Cortar a nivel del suelo (sin raíz)', 'Transportar al trapiche en <24 horas (pierde sacarosa)', 'Producción: 80-200 ton/ha/año según variedad'],
        alertas: ['Caña quemada pierde 20% de peso', 'No cosechar con escarcha (congela savia)', 'Cada hora sin procesar pierde 0.05% de sacarosa'] },
    ],
    plagas: [
      { nombre: 'Gusano taladrador (Diatraea saccharalis)', descripcion: 'Perfora tallos, reduce rendimiento. Larvas cavan galerías.', control: 'Trampas con feromonas, insecticidas sistémicos, control biológico con Trichogramma.' },
      { nombre: 'Broca de la caña (Strymon megarus)', descripcion: 'Larvas que taladran brotes jóvenes.', control: 'Insecticidas al momento de siembra, variedades resistentes.' },
      { nombre: 'Roya de la caña (Puccinia melanocephala)', descripcion: 'Hongos que forman pústulas anaranjadas en hojas. Favorecido por humedad.', control: 'Variedades resistentes (H57-5174), fungicidas preventivos, buena ventilación.' },
      { nombre: 'Mosca blanca (Melanaphis sacchari)', descripcion: 'Transmite virus del mosaico. Chupa savia de hojas jóvenes.', control: 'Aceites minerales, insecticidas sistémicos, enemigos naturales.' },
      { nombre: 'Araña roja', descripcion: 'Ataca hojas en clima seco y caluroso.', control: 'Acaricidas, mantener humedad ambiental, rocío de agua.' },
    ],
    manejoSalinidad: {
      descripcion: 'La salinidad es un problema creciente en cañaverales costeños del Perú (Lambayeque, La Libertad, Ica). La variedad H57-5174 ha demostrado tolerancia superior.',
      niveles: [
        { ce: '<2 dSm-1', estado: 'Sin estrés', accion: 'Manejo normal de riego y fertilización.' },
        { ce: '2-4 dSm-1', estado: 'Estrés leve', accion: 'Aumentar riego para lixivar sales. Aplicar mulch. Considerar H57-5174 en nueva siembra.' },
        { ce: '4-8 dSm-1', estado: 'Estrés moderado', accion: 'Solo H57-5174 tolera. Riego por goteo subterráneo. Drenaje subterráneo. Reducir dosis de fertilizante.' },
        { ce: '>8 dSm-1', estado: 'Estrés severo', accion: 'Solo H57-5174 puede sobrevivir. Considerar descanso de campo o cultivo alternativo.' },
      ],
    },
  },
  {
    id: 'platano',
    nombre: 'Plátano',
    emoji: '🍌',
    categoria: 'frutal',
    variedades: ['Sedita', 'Bellaco', 'Isla', 'Palillo', 'Guineo'],
    ciclo: [
      { id: 'preparacion',     nombre: 'Preparación del terreno', emoji: '🚜', diasInicio: -30, diasFin: 0,
        acciones: ['Eliminar plántulas viejas y rastrojo', 'Arar a 25cm de profundidad', 'Aplicar estiércol (20-30 ton/ha)', 'Marcar puntos a 2.5m x 2.5m'],
        alertas: ['Suelo con nematodos requiere solarización', 'No replantar donde hubo plátano en 2 años'] },
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 30,
        acciones: ['Usar cormo de planta madre como semilla', 'Plantar a 2.5m x 2.5m', 'Cavar hoyo de 40x40x40cm', 'Aplicar abono de base y humus de lombriz'],
        alertas: ['Cormos con nematodos propagan enfermedad', 'No plantar donde hubo plátano antes de 2 años'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 30,  diasFin: 270,
        acciones: ['Deschupar (eliminar hijuelos) cada 2 meses', 'Dejar solo el tallo principal + 1 reserva', 'Fertilizar NPK cada 3 meses', 'Controlar sigatoka con fungicida preventivo'],
        alertas: ['Sigatoka negra destruye hojas = menos foto-síntesis', 'Tallos débiles se quiebran con viento'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 270, diasFin: 300,
        acciones: ['Cortar la flor macho (macho seco)', 'Proteger racimo del sol (cubrir con hojas)', 'Acomodar tallo con estaca si está inclinado', 'No fumigar cerca de la flor'],
        alertas: ['Flor macho no cortada = frutos pequeños', 'Gusano del racimo perfora frutos'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🍌', diasInicio: 300, diasFin: 330,
        acciones: ['Cubrir racimo con bolsa plástica perforada', 'Eliminar hojas secas (mejorar ventilación)', 'Monitorear tamaño de frutos', 'Mantener riego constante'],
        alertas: ['Pájaros y murciélagos picotean frutos', 'Exceso de viento rompe racimos'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🍌', diasInicio: 330, diasFin: 365,
        acciones: ['Cosechar cuando frutos estén llenos pero verdes', 'Cortar tallo principal (dejar hijuelo)', 'Madurar en sombra a 14-18°C', 'Producción: 15-30 kg/planta/ciclo'],
        alertas: ['Fruto amarillo en árbol = demasiado maduro', 'No refrigerar bajo 13°C (daño por frío)'] },
    ],
  },
  {
    id: 'papaya',
    nombre: 'Papaya',
    emoji: '🍈',
    categoria: 'frutal',
    variedades: ['Hawaiana', 'Solo Sunrise', 'Tainung', 'Maradol', 'Venezolana'],
    ciclo: [
      { id: 'preparacion',     nombre: 'Preparación del terreno', emoji: '🚜', diasInicio: -21, diasFin: 0,
        acciones: ['Preparar semillero con sustrato estéril', 'Germinar semillas en bandejas', 'Aplicar fumigante al suelo si hay nematodos', 'Instalar riego por goteo'],
        alertas: ['Semilla vieja (>2 años) tiene baja germinación', 'Suelo frío retrasa germinación'] },
      { id: 'siembra',         nombre: 'Siembra',                emoji: '🌱', diasInicio: 0,   diasFin: 21,
        acciones: ['Germinar en bandejas con sustrato', 'Semilla remojada 48h previamente', 'Trasplantar cuando planta tenga 15-20cm', 'Plantar a 2m entre plantas'],
        alertas: ['Germinación lenta si temperatura <20°C', 'Plántulas extremadamente sensibles a exceso de agua'] },
      { id: 'crecimiento',     nombre: 'Crecimiento vegetativo', emoji: '🌿', diasInicio: 21,  diasFin: 120,
        acciones: ['Riego diario por goteo (2-3L/planta/día)', 'Fertilizar con NPK cada 15 días', 'Controlar chancro bacterial con cobre', 'Mulching para conservar humedad'],
        alertas: ['Chancro bacterial mata plantas jóvenes', 'Exceso de nitrógeno = tallo suave'] },
      { id: 'floracion',       nombre: 'Floración',              emoji: '🌸', diasInicio: 120, diasFin: 150,
        acciones: ['No aplicar insecticidas (mata abejas)', 'Atraer polinizadores con flores companion', 'Mantener humedad constante', 'Aplicar calcio para prevenir pudrición'],
        alertas: ['Floración abundante no garantiza fruta', 'Virus de la papaya destruye plantaciones'] },
      { id: 'fructificacion',  nombre: 'Fructificación',         emoji: '🍈', diasInicio: 150, diasFin: 180,
        acciones: ['Raleo de frutos (dejar 15-20 por planta)', 'Cubrir frutos con papel o bolsa', 'Aplicar fungicida contra antracnosis', 'Aumentar riego a 4L/planta/día'],
        alertas: ['Antracnosis mancha frutos (no son comerciales)', 'Mosca de la fruta pica frutos maduros'] },
      { id: 'cosecha',         nombre: 'Cosecha',                emoji: '🍈', diasInicio: 180, diasFin: 210,
        acciones: ['Cosechar cuando empiece a amarillar', 'No esperar a que esté totalmente madura', 'Manejar con cuidado (se daña fácil)', 'Producción: 30-60 frutos/planta/año'],
        alertas: ['Fruto maduro se pudre en 2-3 días', 'Cortar tallo base para obtener nueva plantación'] },
    ],
  },
];
